-- ==========================================================
-- SCRIPT COMPLET PL/SQL - JOC D'EN PINGU
-- Aquest script implementa els 11 punts de la documentació tècnica.
-- ==========================================================

-- 1. SEQÜÈNCIA: SEC_ID_PARTIDA
CREATE SEQUENCE SEC_ID_PARTIDA START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. TRIGGER: TRG_ID_PARTIDA (Assignació automàtica d'ID)
CREATE OR REPLACE TRIGGER TRG_ID_PARTIDA
BEFORE INSERT ON PARTIDA
FOR EACH ROW
BEGIN
  IF :NEW.ID_PARTIDA IS NULL THEN
    SELECT SEC_ID_PARTIDA.NEXTVAL INTO :NEW.ID_PARTIDA FROM DUAL;
  END IF;
END;
/

-- 3. TRIGGER: TRG_ACTUALITZA_VICTORIES (Suma victòries al guanyador)
CREATE OR REPLACE TRIGGER TRG_ACTUALITZA_VICTORIES
AFTER UPDATE OF FINALITZADA ON PARTIDA
FOR EACH ROW
WHEN (NEW.FINALITZADA = 1 AND OLD.FINALITZADA = 0 AND NEW.ID_GUANYADOR IS NOT NULL)
BEGIN
    UPDATE JUGADOR SET VICTORIES = NVL(VICTORIES, 0) + 1
    WHERE ID_JUGADOR = :NEW.ID_GUANYADOR;
END;
/

-- 4. FUNCIÓ: GET_MAX_VICTORIES_RECORD
CREATE OR REPLACE FUNCTION GET_MAX_VICTORIES_RECORD RETURN NUMBER IS
    v_max NUMBER;
BEGIN
    SELECT MAX(VICTORIES) INTO v_max FROM JUGADOR;
    RETURN NVL(v_max, 0);
END;
/

-- 5. PROCEDIMENT: GET_JUGADORS_RECORD
CREATE OR REPLACE PROCEDURE GET_JUGADORS_RECORD(p_cursor OUT SYS_REFCURSOR) IS
BEGIN
    OPEN p_cursor FOR
        SELECT NOM_JUGADOR, VICTORIES FROM JUGADOR
        WHERE VICTORIES = (SELECT MAX(VICTORIES) FROM JUGADOR) AND VICTORIES > 0;
END;
/

-- 6. FUNCIÓ: GET_MITJA_VICTORIES
CREATE OR REPLACE FUNCTION GET_MITJA_VICTORIES RETURN NUMBER IS
    v_mitja NUMBER;
BEGIN
    SELECT AVG(VICTORIES) INTO v_mitja FROM JUGADOR;
    RETURN NVL(v_mitja, 0);
END;
/

-- 7. PROCEDIMENT: GET_JUGADORS_SOBRE_MITJA
CREATE OR REPLACE PROCEDURE GET_JUGADORS_SOBRE_MITJA(p_cursor OUT SYS_REFCURSOR) IS
BEGIN
    OPEN p_cursor FOR
        SELECT NOM_JUGADOR, VICTORIES FROM JUGADOR
        WHERE VICTORIES > (SELECT AVG(VICTORIES) FROM JUGADOR)
        ORDER BY VICTORIES DESC;
END;
/

-- 8. FUNCIÓ: PERCENTATGE_MENYS_VICTORIES (Necessària pel punt 9)
CREATE OR REPLACE FUNCTION PERCENTATGE_MENYS_VICTORIES(p_vics IN NUMBER) RETURN NUMBER IS
    v_total NUMBER;
    v_menys NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total FROM JUGADOR;
    IF v_total = 0 THEN RETURN 0; END IF;
    SELECT COUNT(*) INTO v_menys FROM JUGADOR WHERE VICTORIES < p_vics;
    RETURN (v_menys / v_total) * 100;
END;
/

-- 9. TRIGGER: TRG_AVIS_RANKING (El que no entenies)
CREATE OR REPLACE TRIGGER TRG_AVIS_RANKING
AFTER UPDATE OF VICTORIES ON JUGADOR
FOR EACH ROW
DECLARE
    v_perc NUMBER;
BEGIN
    v_perc := PERCENTATGE_MENYS_VICTORIES(:NEW.VICTORIES);
    DBMS_OUTPUT.PUT_LINE('RANKING: El jugador ' || :NEW.NOM_JUGADOR
        || ' ara supera al ' || ROUND(v_perc, 2) || '% dels jugadors.');
END;
/

-- 10. PROCEDIMENT: RANKING_PARTIDES_TOTALS
CREATE OR REPLACE PROCEDURE RANKING_PARTIDES_TOTALS(p_cursor OUT SYS_REFCURSOR) IS
BEGIN
    OPEN p_cursor FOR
        SELECT J.NOM_JUGADOR, COUNT(JP.ID_PARTIDA) AS TOTAL
        FROM JUGADOR J
        LEFT JOIN JUGADOR_PARTIDA JP ON J.ID_JUGADOR = JP.ID_JUGADOR
        GROUP BY J.NOM_JUGADOR
        ORDER BY TOTAL DESC;
END;
/

-- 11. PROCEDIMENT: CONSULTAR_ESTADISTIQUES_JUGADOR (Control d'errors)
CREATE OR REPLACE PROCEDURE CONSULTAR_ESTADISTIQUES_JUGADOR(
    p_nom IN VARCHAR2,
    p_vics OUT NUMBER,
    p_total_partides OUT NUMBER
) IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM JUGADOR WHERE NOM_JUGADOR = p_nom;
    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERROR: El jugador ' || p_nom || ' no existeix.');
    END IF;

    SELECT COUNT(*) INTO p_total_partides
    FROM JUGADOR_PARTIDA JP JOIN JUGADOR J ON J.ID_JUGADOR = JP.ID_JUGADOR
    WHERE J.NOM_JUGADOR = p_nom;

    IF p_total_partides = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERROR: El jugador ' || p_nom || ' encara no ha guardat cap partida.');
    END IF;

    SELECT VICTORIES INTO p_vics FROM JUGADOR WHERE NOM_JUGADOR = p_nom;
END;
/
